version: "2.4"
name: edulib-dev
services:
  db:
    image: mariadb:latest
    container_name: edulib-database
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: edulib_debug
      MYSQL_USER: su123
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --su-mysql --connect"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: edulib/backend 
    container_name: edulib-backend
    ports:
      - "8080:8080"
    env_file:
      - ./BACKEND/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
