name: edulib-dev
services:
  db:
    image: mariadb:latest
    container_name: edulib-database

    env_file:
      - ./BACKEND/.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --su-mysql --connect"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend_server:
    build:
      context: ./BACKEND
    container_name: edulib-backend
    env_file:
      - ./BACKEND/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

    ports:
      - "8080:8080"

  frontend_server:
      build:
        context: ./FRONTEND
      container_name: edulib-frontend
      env_file:
        - ./FRONTEND/.env
      depends_on:
        - backend_server
      restart: unless-stopped
      networks:
        - app-network
      ports:
        - "3000:3000"

  nginx_proxy:
    image: nginx:alpine
    container_name: edulib-proxy
    volumes:
      - ./PROXY/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend_server
      - backend_server

    networks:
      - app-network
    attach: false
networks:
  app-network:

volumes:
  db-data:
